name: Python AI API CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ia_api/requirements.txt

    - name: Run tests # Adicione seus comandos de teste aqui, se tiver
      run: |
        echo "No tests defined yet for Python AI API."
        # python -m pytest ia_api/tests/